pipeline {
    agent any

    stages {

        stage('Network Diagnostics') {
            steps {
                sh '''
                    echo "=== Proxy Variables ==="
                    env | grep -i proxy || true

                    echo "=== Git Proxy ==="
                    git config --get http.proxy || true

                    echo "=== Curl Through Proxy ==="
                    curl -x http://10.47.203.33:3128 -I https://github.com || true
                '''
            }
        }

    }

    post {
        failure {
            script {

                def logUrl = "${BUILD_URL}consoleText"

                def payload = """{
                    "build_id": "${BUILD_NUMBER}",
                    "job_name": "${JOB_NAME}",
                    "log_url": "${logUrl}",
                    "git_author_email": "test_dev@example.com"
                }"""

                echo "Triggering RCA Agent..."

                sh """
                    curl -X POST \
                    'https://obscure-space-memory-gx5q9p6r764v39wrr-8000.app.github.dev/api/v1/analyse' \
                    -H 'Content-Type: application/json' \
                    -d '${payload}'
                """
            }
        }
    }
}